	REAL FUNCTION ZEROCH(AX,F,TOL1,TOL2,DX,FB,IERROR)
!
	LOGICAL FIRST
	REAL AX,FAX,BX,FBX,F,TOL1,TOL2
	REAL A,B,C,D,E,EPS,FA,FB,FC,TOLX,TOLF,XM,P,Q,R,S
	EXTERNAL F
	DATA FIRST / .TRUE. /
!
	CALL GUESS1(AX,FAX,BX,FBX,F,DX,TOL2,IERROR)
	IF (IERROR .NE. 0) RETURN
	IF (FIRST) GO TO 100
!
10	A = AX
	B = BX
	FA = FAX
	FB = FBX
!
20	C = A
	FC = FA
	D = B-A
	E = D
30	IF (ABS(FC) .GE. ABS(FB)) GO TO 40
	A = B
	B = C
	C = A
	FA = FB
	FB = FC
	FC = FA
!
!40	TOLX = 2.0*EPS*ABS(B) + 0.5*TOL1	!ISI - 05/31/05
!	TOLF = 2.0*EPS*ABS(FB) + 0.5*TOL2	!ISI - 05/31/05
!	XM = 0.5*(C - B)				    !ISI - 05/31/05

40	TOLX = TOL1		 !ISI - 05/31/05
	TOLF = TOL2		 !ISI - 05/31/05
	XM = 0.5*(C - B) !ISI - 05/31/05
 	IF (ABS(XM) .LE. TOLX) GO TO 90
	IF (ABS(FB) .LE. TOLF) GO TO 90
!
	IF (ABS(E) .LT. TOLX) GO TO 70
	IF (ABS(FA) .LE. ABS(FB)) GO TO 70
!
	IF (A .NE. C) GO TO 50
	S = FB/FA
	P = 2.0*XM*S
	Q = 1.0 - S
	GO TO 60
!
50	Q = FA/FC
	R = FB/FC
	S = FB/FA
	P = S*(2.0*XM*Q*(Q - R) - (B - A)*(R - 1.0))
	Q = (Q - 1.0)*(R - 1.0)*(S - 1.0)
!
60	IF (P .GT. 0.0) Q = -Q
	P = ABS(P)
!
	IF ((2.0*P) .GE. (3.0*XM*Q - ABS(TOLX*Q))) GO TO 70
	IF (P .GE. ABS(0.5*E*Q)) GO TO 70
	E = D
	D = P/Q
	GO TO 80
!
70	D = XM
	E = D
!
80	A = B
	FA = FB
	IF (ABS(D) .GT. TOLX) B = B + D
	IF (ABS(D) .LE. TOLX) B = B + SIGN(TOLX,XM)
	FB = F(B,IERR)
	IF ((FB*(FC/ABS(FC))) .GT. 0.) GO TO 20
	GO TO 30
!
!	SET ERROR CODES
!	  IERROR = 0, NORMAL RETURN
!	  IERROR = 1, TOLERANCE ON INDEPENDENT VARIABLE EXCEEDED
!	  IERROR = 2, TOLERANCE ON FUNCTION VALUE EXCEEDED
!	  IERROR = 3, TOLERANCES ON INDEPENDENT VARIABLE AND FUNCTION VALUE
!		      EXCEEDED
!
90	ZEROCH = B
	IERROR = 0
	IF (ABS(XM) .GT. TOLX) IERROR = 1
	IF (ABS(FB).GT.TOLF) IERROR = IERROR + 2
	RETURN
!
!	COMPUTE MACHINE PRECISION "EPS"
!
100	EPS = 1.0
110	EPS = EPS/2.0
	ONE = 1.0 + EPS
	IF (ONE .GT. 1.0) GO TO 110
	FIRST = .FALSE.
	GO TO 10
	END
                                                   